version: '3.8'
services:

  test_app:
    container_name: async_backend
    build: .
    command: bash -c "pytest -v no:cacheprovider"
    ports:
      - '9001:9000'
    volumes:
      - /tmp/static:/code/static
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dev
    ports:
      - 6432:5432


volumes:
  postgres_data: