version: '3.8'
services:

  app:
    container_name: async_backend
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 9000"
    ports:
      - '9001:9000'
    volumes:
      - /tmp/static:/code/static
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dev
    ports:
      - 6432:5432


volumes:
  postgres_data: